# Generated by Django 4.1.2 on 2022-11-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=50)),
                ('pet_owner', models.CharField(max_length=50)),
                ('owner_mail', models.EmailField(max_length=254)),
                ('booked_service', models.CharField(max_length=50)),
                ('booked_day', models.DateField()),
                ('booked_time', models.TimeField()),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', models.IntegerField()),
                ('prod_name', models.CharField(max_length=100)),
                ('prod_stock', models.IntegerField()),
                ('prod_img', models.ImageField(upload_to='')),
                ('prod_price', models.IntegerField()),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-prod_id'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('service_prof', models.CharField(max_length=50)),
                ('service_day', models.DateField()),
                ('service_time', models.TimeField()),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
