# Generated by Django 4.1.2 on 2022-11-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='service_day',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service_time',
        ),
        migrations.AddField(
            model_name='services',
            name='service_available',
            field=models.BooleanField(default=True),
        ),
    ]
